#! /bin/sh

input=("./ada-final-public/"*)

for infile in "${input[@]}"; do
	outfile="${infile/%"in"/"out"}"
	./challenge < "${infile}" > "${outfile}"
	./checker "--public" "${infile}" "${outfile}" 
done
